name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-package:
    name: Build and Package for Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
          build-essential checkinstall rpm devscripts fakeroot \
          libgtk-4-dev pkg-config

      - name: Compile the project
        run: |
          make clean
          make all

      - name: Build .tar.gz
        run: |
          mkdir -p dist
          tar -czvf dist/prufus.tar.gz --transform 's,^,prufus/,' .

      - name: Create DEB package
        run: |
          sudo checkinstall --type=debian --install=no \
            --pkgname=prufus --pkgversion=1.0.0 --pkgrelease=1 --pkglicense=MIT \
            --maintainer="Your Name <youremail@example.com>" \
            --pakdir=dist make install

      - name: Create RPM package
        run: |
          sudo checkinstall --type=rpm --install=no \
            --pkgname=prufus --pkgversion=1.0.0 --pkgrelease=1 --pkglicense=MIT \
            --maintainer="Your Name <youremail@example.com>" \
            --pakdir=dist make install

      - name: Generate AppImage
        run: |
          mkdir -p appdir/usr/bin
          cp prufus appdir/usr/bin/
          wget -qO- "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage" > appimagetool
          chmod +x appimagetool
          ./appimagetool appdir dist/prufus.AppImage

      - name: Generate PKGBUILD
        run: |
          mkdir -p dist/PKGBUILD
          echo "pkgname=prufus" > dist/PKGBUILD/PKGBUILD
          echo "pkgver=1.0.0" >> dist/PKGBUILD/PKGBUILD
          echo "pkgrel=1" >> dist/PKGBUILD/PKGBUILD
          echo "arch=('x86_64')" >> dist/PKGBUILD/PKGBUILD
          echo "source=('prufus.tar.gz')" >> dist/PKGBUILD/PKGBUILD
          echo "package() {" >> dist/PKGBUILD/PKGBUILD
          echo "  install -Dm755 prufus \$pkgdir/usr/bin/prufus" >> dist/PKGBUILD/PKGBUILD
          echo "}" >> dist/PKGBUILD/PKGBUILD

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Tarball
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/prufus.tar.gz
          asset_name: prufus.tar.gz
          asset_content_type: application/gzip

      - name: Upload DEB package
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/prufus_1.0.0-1_amd64.deb
          asset_name: prufus_1.0.0-1_amd64.deb
          asset_content_type: application/vnd.debian.binary-package

      - name: Upload RPM package
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/prufus-1.0.0-1.x86_64.rpm
          asset_name: prufus-1.0.0-1.x86_64.rpm
          asset_content_type: application/x-rpm

      - name: Upload AppImage
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/prufus.AppImage
          asset_name: prufus.AppImage
          asset_content_type: application/octet-stream

      - name: Upload PKGBUILD
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/PKGBUILD
          asset_name: PKGBUILD
          asset_content_type: text/plain
